#' Reform data to model inputs
#'
#' @param nc notification counts generated by as_bass_data 
#' @param f_abs results from absorb model if two-step approach applied
#'
#' @return
#' @export
#'
#' @examples
#' nc <- as_bass_data(tail(n_by_country$US, 20), "US", status = "Cumulative")
#' input <- get_absorb_data(nc)
#' 
get_absorb_data <- function(nc) {
  nh <- nc$I
  nhm2 <- rev(rev(nh)[-(1:2)])
  nhm0 <- nh[-(1:2)]
  
  nd <- nc$D
  ndm2 <- rev(rev(nd)[-(1:2)])
  ndm0 <- nd[-(1:2)]
  
  nr <- nc$R
  nrm2 <- rev(rev(nr)[-(1:2)])
  nrm0 <- nr[-(1:2)]
  
  list(
    n_t = length(nh) - 2,
    dh = nhm0 - nhm2,
    dd = ndm0 - ndm2,
    dr = nrm0 - nrm2,
    x1 = nhm0 + nhm2,
    H = nhm0
  )
}


#' @rdname get_absorb_data
#' @export
get_two_step_data <- function(nc, f_abs) {
  nabs <- (nc$I + nc$D + nc$R)[1:(length(nc$I) - 2)]
  
  ni <- rstan::summary(f_abs, pars = "I")$summary[, 1]
  nim2 <- rev(rev(ni)[-(1:2)])
  nim0 <- ni[-(1:2)]
  
  nh <- nc$I[-(1:2)]
  nhm2 <- rev(rev(nh)[-(1:2)])
  nhm0 <- nh[-(1:2)]
  
  mn = max(ni + nabs)
  
  list(
    n_t = length(nabs) - 2,
    di = nim0 - nim2,
    dh = nhm0 - nhm2,
    x1 = nim0 + nim2,
    x2 = nim0 * nim2,
    n_a = length(nabs),
    A = nabs,
    I = ni,
    r_out = sum(rstan::summary(f_abs, pars = c("r_death", "r_rec"))$summary[, 1]),
    m_mn = mn,
    m_mx = mn * 20
  )
}



#' Fit BassSIR model to data with a two step approach
#'
#' @param sel selected data set
#' @param loc location of interest
#' @param r_iso isolation rate (invasion of isolation delay)
#' @param n_iter_1 number of iterations for the absorbing state model
#' @param n_iter_2 number of iterations for the BassSIR model
#' @param n_collect number of iterations being collected as output
#' @param n_chain number of chains 
#' @param thres threshold of Rhat for testing convergance 
#' @param ... argumens for rstan::sampling(...)
#'
#' @return
#' @export
#'
#' @examples
#' f_bass_sir = fit_two_step(tail(n_by_country$US, 20), "US", refresh = 0)
#' summary(f_bass_sir)
#' 
fit_two_step <- function(sel, loc = "X",
                         r_iso = 1/6.1,
                         n_iter_1 = 1E4,
                         n_iter_2 = 1E5,
                         n_collect = 5000,
                         n_chain = 3,
                         thres = 1.02, ...) {
  d <- as_bass_data(sel, loc, status = "Cumulative")
  
  pass <- F
  
  dat1 <- get_absorb_data(d)
  
  f_abs <- sample_absorb(dat1, r_iso, iter = n_iter_1, warmup = n_iter_1 - n_collect, 
                         chain = n_chain, ...)
  
  dat2 <- get_two_step_data(d, f_abs)
  
  f_bass <- suppressWarnings(sample_bass(dat2, r_iso, iter = n_iter_2, warmup = n_iter_2 - n_collect, 
                        chain = n_chain, ...))
  
  
  if (length(f_bass) >= 1) {
    ps <- c(0.025, 0.5, 0.975)
    
    sts <- rbind(rstan::summary(f_abs, pars=c("r_death", "r_rec", "hi_death", "hi_rec"), prob = ps)$summary,
                 rstan::summary(f_bass, pars=c("beta", "kappa", "m", "R0"), prob = ps)$summary)
    
    for (index in c("Rt", "I_hat", "PrEx")) {
      summ <- rstan::summary(f_bass, pars = index, prob = ps)$summary
      sts <- rbind(sts, summ[nrow(summ), ])
    }
    rownames(sts)[(nrow(sts) - 2):nrow(sts)] <- c("Rt", "I_hat", "PrEx")
    
    sts <- sts[, c("mean", "50%", "2.5%", "97.5%")]
    colnames(sts) <- c("mean", "median", "lower", "upper")
    sts <- data.frame(sts)
    
    Rhat <- max(rstan::summary(f_bass, c("m", "beta", "kappa"))$summary[, "Rhat"])
    pass <- Rhat < thres
    
  } else {
    sts <- list()
    Rhat <- Inf
    pass <- F
  }
  
  res <- list(
    Date = sel$Date[nrow(sel)],
    Location = loc,
    Indices = sts,
    Converge = pass,
    Rhat = Rhat,
    Models = list(Absorb = f_abs, Bass = f_bass),
    N_try = 1
  )
  class(res) <- "estBassSIR"
  return(res)
}


#' Summarise a fitted Bass SIR model
#'
#' @param est a model with fitted parameters
#'
#' @return
#' @export
#'
#' @examples
#' f_bass_sir = fit_two_step(tail(n_by_country$US, 20), "US", refresh = 0)
#' summary(f_bass_sir)
#' 
summary.estBassSIR <- function(est) {
  y <- list()
  
  y$EndData <- est$Date
  y$Location <- est$Location
  y$ModelType <- "Two-step BassSIR"
  
  y$Pars <- est$Indices
  
  class(y) <- "summaryEstBassSIR"
  return(y)
}


#' @rdname summary.estBassSIR
#' @export
print.summaryEstBassSIR <- function(est) {
  cat("Country: ", est$Location, "\n")
  cat("Model: ", est$ModelType, "\n")
  for (name in rownames(est$Pars)) {
    cat(name, ": ", est$Pars[name, 1], "(", est$Pars[name, 3], ", ", est$Pars[name, 4], ")\n")
  }
}
